# .lefthook.yaml
---
remotes:
  - git_url: https://github.com/boozt-platform/lefthook.git
    ref: v1.3.0
    configs:

      # lint commit messages based by the conventional commits
      - hooks/commitlint/.lefthook.yaml

      # lint the markdown (.md) files
      - hooks/markdown-lint/.lefthook.yaml

      # A linter for YAML files.
      - hooks/yamllint/.lefthook.yaml
