# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clone < Formula
  desc ""
  homepage ""
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joakimen/clone/releases/download/v0.5.2/clone_0.5.2_darwin_amd64"
      sha256 "4b298a8177221cb828fcb311a9090dbf2fec5c6bcb7c87103cfa3e5693f0bb7b"

      def install
        bin.install "clone_0.5.2_darwin_amd64" => "clone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joakimen/clone/releases/download/v0.5.2/clone_0.5.2_darwin_arm64"
      sha256 "e091b456983417621f3956d14e6854afee5f4315ad3136662ffafcb27c73f7ac"

      def install
        bin.install "clone_0.5.2_darwin_arm64" => "clone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/clone/releases/download/v0.5.2/clone_0.5.2_linux_amd64"
        sha256 "bb4eecb9594a3f56b8dddbfc1928bed91b6fca58f84ae22f289000308e617dde"

        def install
          bin.install "clone_0.5.2_linux_amd64" => "clone"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/clone/releases/download/v0.5.2/clone_0.5.2_linux_arm64"
        sha256 "b308cad72fbe2331daef4a41beda756058f3c0c47dd9a2b1b6b3727200ef03dd"

        def install
          bin.install "clone_0.5.2_linux_arm64" => "clone"
        end
      end
    end
  end
end
