# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clone < Formula
  desc ""
  homepage ""
  version "0.6.1"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joakimen/clone/releases/download/v0.6.1/clone_0.6.1_darwin_amd64"
      sha256 "5ca53ef66b3baff1963c0307a270dcc2820112cbd77932365f047f370e020ccf"

      def install
        bin.install "clone_0.6.1_darwin_amd64" => "clone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joakimen/clone/releases/download/v0.6.1/clone_0.6.1_darwin_arm64"
      sha256 "ea17a9ca9418570a90cc0ba5116d7e59baa5018be46012a5e91b3d8703b5652e"

      def install
        bin.install "clone_0.6.1_darwin_arm64" => "clone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/clone/releases/download/v0.6.1/clone_0.6.1_linux_amd64"
        sha256 "3ecff2c9d6fa0aaaccf7faad8495f99968ee224b53bbcd591223030be3a66044"

        def install
          bin.install "clone_0.6.1_linux_amd64" => "clone"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/clone/releases/download/v0.6.1/clone_0.6.1_linux_arm64"
        sha256 "a50a52b3b984618ee8584a6325186981b04827f15327b451b7ba530cf50e06c9"

        def install
          bin.install "clone_0.6.1_linux_arm64" => "clone"
        end
      end
    end
  end
end
