# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clone < Formula
  desc ""
  homepage ""
  version "0.6.2"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joakimen/clone/releases/download/v0.6.2/clone_0.6.2_darwin_amd64"
      sha256 "ac2aa10ef0a294b374d1839aef31c55bca1539193361914398e3c4b809ea7216"

      def install
        bin.install "clone_0.6.2_darwin_amd64" => "clone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joakimen/clone/releases/download/v0.6.2/clone_0.6.2_darwin_arm64"
      sha256 "edf8ae9b6f0de227cc69b9d1337d1e0d4b573e38b043d9cd31bd8d5406db5ede"

      def install
        bin.install "clone_0.6.2_darwin_arm64" => "clone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/clone/releases/download/v0.6.2/clone_0.6.2_linux_amd64"
        sha256 "3eb4d97eaef98ad086fe449242b53634b4a52d35d2c1858985862bc142464e91"

        def install
          bin.install "clone_0.6.2_linux_amd64" => "clone"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/clone/releases/download/v0.6.2/clone_0.6.2_linux_arm64"
        sha256 "47c4b0ba3123553f74928770099c4796c3503a8dc93c602e26ffb9b998215290"

        def install
          bin.install "clone_0.6.2_linux_arm64" => "clone"
        end
      end
    end
  end
end
