# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc ""
  homepage ""
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joakimen/gg/releases/download/v0.9.0/gg_0.9.0_darwin_amd64"
      sha256 "ce0aa97303380cc21aa9369f6cf6cc3b09791d53b4bafb807cdc46ddcdbdb630"

      def install
        bin.install "gg_0.9.0_darwin_amd64" => "gg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joakimen/gg/releases/download/v0.9.0/gg_0.9.0_darwin_arm64"
      sha256 "2cc99474723afe0f01449aa3f2be9fb3b589aceb4630519af7faa2ffab87fc29"

      def install
        bin.install "gg_0.9.0_darwin_arm64" => "gg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/gg/releases/download/v0.9.0/gg_0.9.0_linux_amd64"
        sha256 "d832e75f085ab0f608105bb880cdb7105fa20b3e32d32c68a3d8e8b874740b28"

        def install
          bin.install "gg_0.9.0_linux_amd64" => "gg"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/gg/releases/download/v0.9.0/gg_0.9.0_linux_arm64"
        sha256 "ef677e85c3145cb0f96cd4be6fc332aeddd7a489914f5829e17d8ea68fb8a66e"

        def install
          bin.install "gg_0.9.0_linux_arm64" => "gg"
        end
      end
    end
  end
end
