# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc ""
  homepage ""
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joakimen/gg/releases/download/v0.8.0/gg_0.8.0_darwin_amd64"
      sha256 "ff70aa4236eefecea7009e0144a377627542fed8ead4ded67808e0940f61cff5"

      def install
        bin.install "gg_0.8.0_darwin_amd64" => "gg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joakimen/gg/releases/download/v0.8.0/gg_0.8.0_darwin_arm64"
      sha256 "31f3e0b417e79aab2e008cb46c57366580078ab4fe978d477335922b18b0c2e2"

      def install
        bin.install "gg_0.8.0_darwin_arm64" => "gg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/gg/releases/download/v0.8.0/gg_0.8.0_linux_amd64"
        sha256 "0d22d43744ecd8db7c8aeb45b08506ebd49e25cda71d5dc05bda81bd863355c5"

        def install
          bin.install "gg_0.8.0_linux_amd64" => "gg"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/gg/releases/download/v0.8.0/gg_0.8.0_linux_arm64"
        sha256 "d4aa328b15234e8a7b476a0736dc495311a0777f3aa203a01520657b179ad56b"

        def install
          bin.install "gg_0.8.0_linux_arm64" => "gg"
        end
      end
    end
  end
end
