# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc ""
  homepage ""
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joakimen/gg/releases/download/v0.8.1/gg_0.8.1_darwin_amd64"
      sha256 "3dc93d70559c351f74eca16244e86afccc82f792889907bdb314e673e24fbed6"

      def install
        bin.install "gg_0.8.1_darwin_amd64" => "gg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joakimen/gg/releases/download/v0.8.1/gg_0.8.1_darwin_arm64"
      sha256 "7067cac6bccb0589946c7d53c267ab37e82c8762f0a7f85fe0c90d7786b3aba2"

      def install
        bin.install "gg_0.8.1_darwin_arm64" => "gg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/gg/releases/download/v0.8.1/gg_0.8.1_linux_amd64"
        sha256 "232aaa5714e0e62a1faa62838184d9f8793223e1cff962ef57fb3080cc59da80"

        def install
          bin.install "gg_0.8.1_linux_amd64" => "gg"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/joakimen/gg/releases/download/v0.8.1/gg_0.8.1_linux_arm64"
        sha256 "19c8e064c782c16e568020fa4082e0f0e18466598ea0f205fa865416b510d572"

        def install
          bin.install "gg_0.8.1_linux_arm64" => "gg"
        end
      end
    end
  end
end
